version: '3.4'

services:
  web:
    image: smartdocflask
    command: flask run --host=0.0.0.0 --port=80
    environment: 
      - FLASK_APP=app.py
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    ports:
      - 5000